services:
  n8n:
    #image: docker.n8n.io/n8nio/n8n
    image: docker.home.rift-way.win/homelab/n8n-python:1.102.1-7
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n-p1.${DOMAIN_NAME}
      - WEBHOOK_URL=https://n8n-p1.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - ./n8n_data/:/home/node/.n8n

